services:
  # Backend API Service
  - type: web
    name: designer-listings-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:create_app()
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app

  # Frontend Static Site
  - type: web
    name: designer-listings-frontend
    env: static
    buildCommand: echo "No build required"
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 